repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
        # Exclude path where we currently store some keys. TODO: this might need to evolve in the future
        exclude: (scripts/internal/keys/|oka/applications/ait/tests/Data/licensemgr/|oka/oka/lib/common/licenseConstants.py)
      - id: check-symlinks
        exclude: \.env  # We keep this one as it is useful for developments
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: no-commit-to-branch
        args: [--branch, release, --branch, dev]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-mypy, flake8-colors, pep8-naming]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['-w 150', '-t py37']

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['-l 150']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', '-c', '.bandit.ini', '--exclude', '**/tests/*']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        files: (.*\.rst)|(.*\.txt)
        args: ['--builtin', 'clear,rare,informal,names,en-GB_to_en-US']
