# Generated by Django 5.0 on 2023-12-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(default="", max_length=10),
        ),
    ]
