# Generated by Django 5.0.1 on 2024-01-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(choices=[("personnel", "Personnel"), ("management", "Management")], default="personnel", max_length=200),
        ),
    ]
