# Generated by Django 5.0.1 on 2024-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_aircraft_part_aircraftpartusage_teamprofile_parts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="production",
            name="part",
        ),
        migrations.AddField(
            model_name="production",
            name="parts",
            field=models.ManyToManyField(related_name="productions", to="core.part"),
        ),
    ]
