# Generated by Django 5.0.1 on 2024-10-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_production_parts_production_aircraft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="required_parts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="production",
            name="aircraft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.aircraft",
            ),
            preserve_default=False,
        ),
    ]
